# -*- coding: utf-8 -*-
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
import webbrowser


import os
ROOT_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath('YOUniversity')))) # Percorso della cartella di progetto -> C:\\Users\\NomeUtente\\Cartella

sys.path.append(ROOT_DIR + '\\YOUniversity\\PathFinding')

#sys.path.append('C:\\Users\\Cugggino\\YOUniversity\\YOUniversity\\PathFinding')
from PathFinding import findLocationsPath, ROOT_DIR
from GeoLocationsUtilities import Location, loadLocations

from PyQt5 import QtCore, QtGui, QtWidgets

MAP_FILE_PATH = ROOT_DIR + "\\resources\\locations\\Bari.csv"
#MAP_FILE_PATH = "C:\\Users\\Cugggino\\YOUniversity\\resources\\locations\\Bari.csv"

class Ui_Dialog_FindUs(object):
  
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(579, 473)
        
        
        self.comboBoxStart = QtWidgets.QComboBox(Dialog)
        self.comboBoxStart.setGeometry(QtCore.QRect(240, 60, 281, 31))
        self.comboBoxStart.setObjectName("comboBoxStart")
        #self.comboBoxStart.addItem("")
        self.comboBoxGoal = QtWidgets.QComboBox(Dialog)
        self.comboBoxGoal.setGeometry(QtCore.QRect(240, 110, 281, 31))
        self.comboBoxGoal.setObjectName("comboBoxGoal")
        #  self.comboBoxGoal.addItem("")
      
        for p in self.pointsSet:
           self.comboBoxStart.addItem(p)
          
        self.comboBoxGoal.addItem("Ateneo-Piazza Cesare Battisti(1)")
        self.comboBoxGoal.addItem("Facoltà di Economia-Largo Abbazia Santa Scolastica")
        self.comboBoxGoal.addItem("Policlinico-Piazza Giulio Cesare")
        self.comboBoxGoal.addItem("Politecnico/Campus-Via Edoardo Orabona")
        
        self.labelTitle = QtWidgets.QLabel(Dialog)
        self.labelTitle.setGeometry(QtCore.QRect(130, 10, 341, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setKerning(True)
        self.labelTitle.setFont(font)
        self.labelTitle.setObjectName("labelTitle")
        self.labelStart = QtWidgets.QLabel(Dialog)
        self.labelStart.setGeometry(QtCore.QRect(50, 60, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelStart.setFont(font)
        self.labelStart.setObjectName("labelStart")
        self.labelGoal = QtWidgets.QLabel(Dialog)
        self.labelGoal.setGeometry(QtCore.QRect(50, 110, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelGoal.setFont(font)
        self.labelGoal.setObjectName("labelGoal")
        self.pushButtonSearch = QtWidgets.QPushButton(Dialog)
        self.pushButtonSearch.setGeometry(QtCore.QRect(240, 160, 281, 31))
        self.pushButtonSearch.setAutoDefault(False)
        self.pushButtonSearch.setObjectName("pushButton")
        self.commandLinkButtonViewBrowser = QtWidgets.QCommandLinkButton(Dialog)
        self.commandLinkButtonViewBrowser.setGeometry(QtCore.QRect(220, 430, 341, 41))
        self.commandLinkButtonViewBrowser.setAutoDefault(False)
        self.commandLinkButtonViewBrowser.setObjectName("commandLinkButtonViewBrowser")
    
        self.commandLinkButtonViewBrowser.hide() #Viene mostrato solo dopo aver premuto il tasto di ricerca
             
        self.pushButtonMapView = QtWidgets.QPushButton(Dialog)
        self.pushButtonMapView.setGeometry(QtCore.QRect(40, 210, 491, 221))
        self.pushButtonMapView.setText("")
        self.pushButtonMapView.setObjectName("pushButtonMapView")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(ROOT_DIR + "\\resources\\images\\map\\map.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonMapView.setIcon(icon)
        self.pushButtonMapView.setIconSize(QtCore.QSize(491, 221))
        self.pushButtonMapView.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Come raggiungere il tuo dipartimento"))
        
        #aggiungo le combo box di partenza e destinazione
        i = 0
        
        for p in self.pointsSet:
            self.comboBoxStart.setItemText(i, _translate("Dialog", p))
            i = i + 1 
        
        self.comboBoxGoal.setItemText(0, _translate("Dialog", "Ateneo-Piazza Cesare Battisti(1)"))
        self.comboBoxGoal.setItemText(1, _translate("Dialog", "Facoltà di Economia-Largo Abbazia Santa Scolastica"))
        self.comboBoxGoal.setItemText(2, _translate("Dialog", "Policlinico-Piazza Giulio Cesare"))
        self.comboBoxGoal.setItemText(3, _translate("Dialog", "Politecnico/Campus-Via Edoardo Orabona"))
        
        self.labelTitle.setText(_translate("Dialog", "Come raggiungere il tuo dipartimento"))
        self.labelStart.setText(_translate("Dialog", "Seleziona la partenza:"))
        
        self.labelGoal.setText(_translate("Dialog", "Seleziona la destinazione:"))
        self.pushButtonSearch.setText(_translate("Dialog", "Calcola il percorso migliore"))
        self.commandLinkButtonViewBrowser.setText(_translate("Dialog", "Visualizza il percorso dal browser"))

        self.pushButtonSearch.clicked.connect(self.searchPath)
        self.pushButtonMapView.setToolTip("Clicca qui per visualizzare la mappa completa da browser")
        self.pushButtonMapView.clicked.connect(self.viewMap)
        self.pushButtonMapView.setAutoDefault(False)
                
        self.pushButtonGoBack = QtWidgets.QPushButton(Dialog)
        self.pushButtonGoBack.setGeometry(QtCore.QRect(10, 10, 40, 40))
        self.pushButtonGoBack.setMaximumSize(QtCore.QSize(49, 49))
        self.pushButtonGoBack.setObjectName("pushButtonGoBack")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(ROOT_DIR + "\\resources\\images\\menu\\goBack.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonGoBack.setStyleSheet("background-color: rgb(55,117,169);")
        self.pushButtonGoBack.setIcon(icon)
        self.pushButtonGoBack.setIconSize(QtCore.QSize(49,49))
        self.pushButtonGoBack.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.pushButtonGoBack.clicked.connect(Dialog.close)
        
        
        self.commandLinkButtonViewBrowser.clicked.connect(self.openTab)
    
    def __init__(self):
        self.pointsSet = set() 
        
        self.points = []
        self.streets = []
        self.points, self.streets = loadLocations(MAP_FILE_PATH) 
    
        for p in self.points:
            self.pointsSet.add(p.getValue().getName())

      
        self.pointsSet = list(self.pointsSet) #converte il set in lista per poterlo ordinare
        #print(self.pointsSet)
        self.pointsSet.sort()
        #print(self.pointsSet)
 
    def searchPath(self):
        
        for p in self.points:
            if p.getValue().getName() == self.comboBoxStart.currentText():
                start = p
            if p.getValue().getName() == self.comboBoxGoal.currentText():
                dest = p

        cost=findLocationsPath(Location(start.getValue().getX(), start.getValue().getY(), start.getValue().getName()), Location(dest.getValue().getX(), dest.getValue().getY(), dest.getValue().getName()), MAP_FILE_PATH)  
        #TODO LABEL
        self.commandLinkButtonViewBrowser.show()        
    
    def viewMap(self):
        webbrowser.open_new_tab("mymap.html")   
    def openTab(self):
        webbrowser.open_new_tab("resultmap.html")
         
if __name__ == "__main__":
    import sys
    
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog(None, QtCore.Qt.WindowSystemMenuHint | QtCore.Qt.WindowCloseButtonHint)
    ui = Ui_Dialog_FindUs()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
